#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker2"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "860d234e9b8f4d0bb46fe4de1fa15257" }
]

[assets]
directory = "./public"
